POST https://nodejs-api-09jc.onrender.com/videos
Content-Type: application/json

{ 
  "title": "Video node",
  "description": "Esse é o primeiro vídeo",
  "duration": 180
}

###

GET https://nodejs-api-09jc.onrender.com/videos

###
PUT https://nodejs-api-09jc.onrender.com/videos/c3845fff-5a66-41e7-9f25-97a32ec3f78e
Content-Type: application/json

{
  "title": "Video Teste",
  "description": "Esse é o primeiro vídeo",
  "duration": 180
}

###
DELETE https://nodejs-api-09jc.onrender.com/videos/c3845fff-5a66-41e7-9f25-97a32ec3f78e
