POST http://localhost:3333/videos
Content-Type: application/json

{ 
  "title": "Video node",
  "description": "Esse é o primeiro vídeo",
  "duration": 180
}

###

GET http://localhost:3333/videos

###
PUT http://localhost:3333/videos/7a45b9ae-a612-40c7-86ef-a8315442b729
Content-Type: application/json

{
  "title": "Video 02",
  "description": "Esse é o primeiro vídeo",
  "duration": 180
}

###
DELETE http://localhost:3333/videos/7a45b9ae-a612-40c7-86ef-a8315442b729
